DROP TABLE IF EXISTS film_genre;
DROP TABLE IF EXISTS mpas CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS genres CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS friends CASCADE;

CREATE TABLE IF NOT EXISTS mpas
    (
    mpa_id Integer PRIMARY KEY,
    name varchar NOT NULL
    );

CREATE TABLE IF NOT EXISTS films
    (
    film_id Integer PRIMARY KEY AUTO_INCREMENT,
    name varchar NOT NULL,
    description varchar(200),
    release_date date,
    duration Integer,
    mpa_id Integer REFERENCES mpas (mpa_id)
    );

CREATE TABLE IF NOT EXISTS genres
    (
    genre_id Integer PRIMARY KEY,
    name varchar(100)
    );

CREATE TABLE IF NOT EXISTS film_genre
    (
    film_id Integer REFERENCES films (film_id),
    genre_id Integer REFERENCES genres (genre_id),
    PRIMARY KEY (film_id, genre_id)
    );

CREATE TABLE IF NOT EXISTS users
    (
    user_id Integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar,
    login varchar NOT NULL,
    name varchar,
    birthday date
    );

CREATE TABLE IF NOT EXISTS likes
    (
    user_id Integer REFERENCES users (user_id),
    film_id Integer REFERENCES films (film_id),
    PRIMARY KEY (user_id, film_id)
    );

CREATE TABLE IF NOT EXISTS friends
    (
    user_id   Integer REFERENCES users (user_id),
    friend_id Integer REFERENCES users (user_id),
    PRIMARY KEY (user_id, friend_id)
    );